name: Build and Push Docker Compose Images to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  COMPOSE_FILE: docker-compose.yml
  ECR_REPOSITORY_PREFIX: ecr-dev
  IMAGE_PREFIX: gammonx
  GAME_SERVICE: game-service
  WILDBG_SERVICE: wildbg-service
  LAMBDA_SERVICE: lambda-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Compose images
        env:
          DOCKER_DEFAULT_PLATFORM: linux/amd64
        run: |
          docker compose build ${GAME_SERVICE}

      - name: Tag and Push images to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "GAME SERVICE"
          IMAGE_NAME="${ECR_REGISTRY}/${ECR_REPOSITORY_PREFIX}-${GAME_SERVICE}:latest"
          echo "Tagging and pushing $IMAGE_NAME"
          # Tag image
          docker tag "${IMAGE_PREFIX}/${GAME_SERVICE}:latest" "$IMAGE_NAME"
          docker push "$IMAGE_NAME"

          echo "WILDBG SERVICE"
          IMAGE_NAME="${ECR_REGISTRY}/${ECR_REPOSITORY_PREFIX}-${WILDBG_SERVICE}:latest"
          echo "Tagging and pushing $IMAGE_NAME"
          # Tag image
          docker tag "${IMAGE_PREFIX}/${WILDBG_SERVICE}:latest" "$IMAGE_NAME"
          docker push "$IMAGE_NAME"

          echo "LAMBDA SERVICE"
          IMAGE_NAME="${ECR_REGISTRY}/${ECR_REPOSITORY_PREFIX}-${LAMBDA_SERVICE}:latest"
          echo "Tagging and pushing $IMAGE_NAME"
          # Tag image
          docker tag "${IMAGE_PREFIX}/${LAMBDA_SERVICE}:latest" "$IMAGE_NAME"
          docker push "$IMAGE_NAME"
